<?php
include('../database/config.php');

$id_gudang = $_POST['idgudang'];
$id_barang = $_POST['idbarang'];
$id_admin = $_SESSION['id_user'];
$serial_n = $_POST['snunit'];

// Check if the provided id_gudang exists
$gudang_check = $mysqli->query("SELECT * FROM gudang WHERE id_gudang='$id_gudang'");
if ($gudang_check->num_rows == 0) {
    echo "Invalid id_gudang: $id_gudang does not exist in the gudang table.";
    header('Location: ../admin/item-detail.php?id=' . $id_barang); 
    exit();
}

if(empty($serial_n)){
    $barang_q = $mysqli->query("SELECT sku FROM barang WHERE id_barang = $id_barang");
    $barang_data = $barang_q->fetch_object();
    $sku= substr($barang_data->sku, 0, 4);
    $autogenerated_sn = $sku . rand(1,10000);
    if ($mysqli->query("INSERT INTO barang_unit (id_barang, status, id_employee, id_gudang, id_user, comment, serial_number, kondisi) VALUES ('$id_barang', '0', NULL, '$id_gudang', '$id_admin', 'Unit Baru', '$autogenerated_sn', '0')")) {
        header('Location: ../admin/item-detail.php?id=' . $id_barang);   
        exit();
    } else {
        echo "Query error: " . $mysqli->error; // Display the specific error message
        exit();
    }
}

if ($mysqli->query("INSERT INTO barang_unit (id_barang, status, id_employee, id_gudang, id_user, comment, serial_number, kondisi) VALUES ('$id_barang', '0', NULL, '$id_gudang', '$id_admin', 'Unit Baru', '$serial_n', '0')")) {
    header('Location: ../admin/item-detail.php?id=' . $id_barang);   
    exit();
} else {
    echo "Query error: " . $mysqli->error; // Display the specific error message
}
?>
